import React, { useState, useEffect } from 'react';
import { useLocation } from 'react-router-dom';
import { 
  Loader2, 
  Image as ImageIcon, 
  Sparkles, 
  Palette, 
  SlidersHorizontal, 
  Download, 
  Layers, 
  ChevronLeft, 
  ChevronRight, 
  ChevronDown,
  Trash2, 
  Copy, 
  ArrowUp, 
  ArrowDown, 
  Plus, 
  Edit 
} from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import Button from '../components/ui/Button';
import { generateMasterCarousel } from '../services/llmService';
import { validateCarouselJSON } from '../services/validationEngine';
import { composeSlides } from '../services/compositionEngine';
import { critiqueAndRefine } from '../services/designCriticEngine';
import { generateDesignSystem, hexToRgba, getContrastText, getLuminance } from '../services/designEngine';
import CarouselRenderer from '../components/editor/CarouselRenderer';
import { exportToPDF, exportToPNGs } from '../services/exportUtility';
import { ErrorBoundary } from '../components/ErrorBoundary';
import './DashboardPage.css';

const slideVariants = {
  enter: (direction) => ({
    x: direction > 0 ? 300 : -300,
    opacity: 0
  }),
  center: {
    x: 0,
    opacity: 1
  },
  exit: (direction) => ({
    x: direction < 0 ? 300 : -300,
    opacity: 0
  })
};

const THEME_PRESETS = [
  {
    id: 'ai-generated',
    label: 'AI Creative',
    emoji: '✨',
    desc: 'The original theme generated by the AI',
    colors: null
  },
  {
    id: 'tech-minimal',
    label: 'Tech Minimalist',
    emoji: '🍏',
    desc: 'Apple-inspired clean fonts and light gray backdrops',
    colors: {
      Primary: '#000000',
      Secondary: '#1d1d1f',
      Accent: '#0066cc',
      Background: '#f5f5f7',
      Surface: '#ffffff',
      Text: '#1d1d1f',
      TextMuted: '#86868b'
    },
    fonts: {
      HeadingFont: '-apple-system, BlinkMacSystemFont, "SF Pro Display", sans-serif',
      BodyFont: '-apple-system, BlinkMacSystemFont, "SF Pro Text", sans-serif'
    }
  },
  {
    id: 'cyberpunk',
    label: 'Cyberpunk Neon',
    emoji: '🖲️',
    desc: 'Dark cyber theme with neon cyan and magenta glow',
    colors: {
      Primary: '#00ffff',
      Secondary: '#ff00ff',
      Accent: '#ff003c',
      Background: '#09090b',
      Surface: '#18181b',
      Text: '#ffffff',
      TextMuted: '#a1a1aa'
    },
    fonts: {
      HeadingFont: '"Space Mono", monospace',
      BodyFont: '"Inter", sans-serif'
    }
  },
  {
    id: 'luxury',
    label: 'Luxury Gold',
    emoji: '⚜️',
    desc: 'High-end gold accents on pure black editorial layouts',
    colors: {
      Primary: '#d4af37',
      Secondary: '#1a1a1a',
      Accent: '#d4af37',
      Background: '#050505',
      Surface: '#121212',
      Text: '#ffffff',
      TextMuted: '#a3a3a3'
    },
    fonts: {
      HeadingFont: '"Playfair Display", serif',
      BodyFont: '"Montserrat", sans-serif'
    }
  },
  {
    id: 'nature',
    label: 'Forest Organic',
    emoji: '🌿',
    desc: 'Earthy green palettes and warm typography',
    colors: {
      Primary: '#166534',
      Secondary: '#14532d',
      Accent: '#eab308',
      Background: '#f0fdf4',
      Surface: '#dcfce7',
      Text: '#064e3b',
      TextMuted: '#166534'
    },
    fonts: {
      HeadingFont: '"Lora", serif',
      BodyFont: '"Inter", sans-serif'
    }
  },
  {
    id: 'sunset',
    label: 'Sunset Warmth',
    emoji: '🌇',
    desc: 'Warm terracotta background with sunset yellow accents',
    colors: {
      Primary: '#c2410c',
      Secondary: '#ea580c',
      Accent: '#f59e0b',
      Background: '#fff7ed',
      Surface: '#ffedd5',
      Text: '#431407',
      TextMuted: '#9a3412'
    },
    fonts: {
      HeadingFont: '"Outfit", sans-serif',
      BodyFont: '"Plus Jakarta Sans", sans-serif'
    }
  }
];

export default function DashboardPage() {
  const location = useLocation();
  const initialPrompt = location.state?.initialPrompt || '';
  
  const [isGenerating, setIsGenerating] = useState(!!initialPrompt);
  const [hasContent, setHasContent] = useState(false);
  const [generationError, setGenerationError] = useState(null);
  
  // Pipeline State
  const [aiAnalysis, setAiAnalysis] = useState(null);
  const [creativeBrief, setCreativeBrief] = useState(null);
  const [moodboard, setMoodboard] = useState(null);
  const [storyPlan, setStoryPlan] = useState(null);
  const [designDNA, setDesignDNA] = useState(null);
  const [criticReport, setCriticReport] = useState(null);
  
  // Design System State
  const [designSystem, setDesignSystem] = useState(null);
  const [originalDesignSystem, setOriginalDesignSystem] = useState(null);
  const [activeTheme, setActiveTheme] = useState('ai-generated');

  // Slides State
  const [slides, setSlides] = useState([]);
  const [activeSlideIndex, setActiveSlideIndex] = useState(0);
  const [direction, setDirection] = useState(0);

  // Aspect Ratio & Sidebar Tab States
  const [aspectRatio, setAspectRatio] = useState('4:5');
  const [rightSidebarTab, setRightSidebarTab] = useState('organizer'); // 'organizer' | 'content'

  const navigateToSlide = (newIndex) => {
    if (newIndex < 0 || newIndex >= slides.length) return;
    setDirection(newIndex > activeSlideIndex ? 1 : -1);
    setActiveSlideIndex(newIndex);
  };

  // Keyboard arrow controls
  useEffect(() => {
    const handleKeyDown = (e) => {
      // Ignore key events if typing in form inputs
      if (document.activeElement.tagName === 'INPUT' || document.activeElement.tagName === 'TEXTAREA') {
        return;
      }
      if (e.key === 'ArrowLeft' && activeSlideIndex > 0) {
        navigateToSlide(activeSlideIndex - 1);
      } else if (e.key === 'ArrowRight' && activeSlideIndex < slides.length - 1) {
        navigateToSlide(activeSlideIndex + 1);
      }
    };
    
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [activeSlideIndex, slides.length]);

  // Export state & handlers
  const [showExportDropdown, setShowExportDropdown] = useState(false);
  const [isExporting, setIsExporting] = useState(false);

  const handleExportPDF = async () => {
    setShowExportDropdown(false);
    setIsExporting(true);
    try {
      const topicName = aiAnalysis?.topic || 'carousel';
      await exportToPDF(slides, designSystem, `${topicName.replace(/\s+/g, '_')}.pdf`, aspectRatio);
    } catch (error) {
      console.error("Export PDF failed", error);
    } finally {
      setIsExporting(false);
    }
  };

  const handleExportPNGs = async () => {
    setShowExportDropdown(false);
    setIsExporting(true);
    try {
      const topicName = aiAnalysis?.topic || 'carousel';
      await exportToPNGs(slides, designSystem, topicName, aspectRatio);
    } catch (error) {
      console.error("Export PNGs failed", error);
    } finally {
      setIsExporting(false);
    }
  };

  // Accordion State
  const [openAccordions, setOpenAccordions] = useState({ 
    brief: false, 
    moodboard: false, 
    plan: false, 
    dna: false, 
    critic: false, 
    customizer: false,
    theme: true
  });
  const toggleAccordion = (key) => setOpenAccordions(prev => ({ ...prev, [key]: !prev[key] }));

  // Card Customizer State
  const [activeCardPreset, setActiveCardPreset] = useState('ai-mix');
  const [customCardHex, setCustomCardHex] = useState('#6366f1');

  const CARD_PRESETS = [
    { id: 'ai-mix', label: 'AI Smart Mix', emoji: '✨' },
    { id: 'primary-tint', label: 'Primary Tint', emoji: '🎨' },
    { id: 'secondary-tint', label: 'Secondary Tint', emoji: '🌊' },
    { id: 'accent-solid', label: 'Accent Pop', emoji: '⚡' },
    { id: 'glass-neutral', label: 'Glass Neutral', emoji: '🪟' },
    { id: 'dark-matte', label: 'Dark Matte', emoji: '🌑' },
    { id: 'custom', label: 'Custom Color', emoji: '🎯' },
  ];

  const applyCardPreset = (presetId, hex) => {
    if (!designSystem) return;
    setActiveCardPreset(presetId);
    const palette = designSystem.ColorPalette;
    let newCardStyles;

    switch (presetId) {
      case 'ai-mix':
        newCardStyles = {
          Background: designSystem._originalCardBg || designSystem.CardStyles.Background,
          Border: designSystem._originalCardBorder || designSystem.CardStyles.Border,
          CardText: designSystem._originalCardText || designSystem.CardStyles.CardText,
          CardTextMuted: designSystem._originalCardTextMuted || designSystem.CardStyles.CardTextMuted,
          BackdropFilter: 'blur(12px)'
        };
        break;
      case 'primary-tint':
        newCardStyles = {
          Background: hexToRgba(palette.Primary, 0.15),
          Border: `1px solid ${hexToRgba(palette.Primary, 0.2)}`,
          CardText: palette.Text,
          CardTextMuted: palette.TextMuted,
          BackdropFilter: 'blur(12px)'
        };
        break;
      case 'secondary-tint':
        newCardStyles = {
          Background: hexToRgba(palette.Secondary, 0.15),
          Border: `1px solid ${hexToRgba(palette.Secondary, 0.2)}`,
          CardText: palette.Text,
          CardTextMuted: palette.TextMuted,
          BackdropFilter: 'blur(12px)'
        };
        break;
      case 'accent-solid':
        newCardStyles = {
          Background: hexToRgba(palette.Accent, 0.85),
          Border: `1px solid ${hexToRgba(palette.Accent, 0.9)}`,
          CardText: getContrastText(palette.Accent),
          CardTextMuted: getContrastText(palette.Accent) === '#ffffff' ? 'rgba(255,255,255,0.7)' : 'rgba(0,0,0,0.5)',
          BackdropFilter: 'none'
        };
        break;
      case 'glass-neutral':
        newCardStyles = {
          Background: 'rgba(255, 255, 255, 0.12)',
          Border: '1px solid rgba(255, 255, 255, 0.15)',
          CardText: palette.Text,
          CardTextMuted: palette.TextMuted,
          BackdropFilter: 'blur(16px)'
        };
        break;
      case 'dark-matte':
        newCardStyles = {
          Background: 'rgba(15, 15, 20, 0.85)',
          Border: '1px solid rgba(255, 255, 255, 0.06)',
          CardText: '#ffffff',
          CardTextMuted: 'rgba(255, 255, 255, 0.55)',
          BackdropFilter: 'blur(8px)'
        };
        break;
      case 'custom':
        newCardStyles = {
          Background: hexToRgba(hex, 0.18),
          Border: `1px solid ${hexToRgba(hex, 0.25)}`,
          CardText: getContrastText(hex),
          CardTextMuted: getContrastText(hex) === '#ffffff' ? 'rgba(255,255,255,0.6)' : 'rgba(0,0,0,0.5)',
          BackdropFilter: 'blur(12px)'
        };
        break;
      default:
        return;
    }

    const updated = { ...designSystem };
    if (!updated._originalCardBg) {
      updated._originalCardBg = designSystem.CardStyles.Background;
      updated._originalCardBorder = designSystem.CardStyles.Border;
      updated._originalCardText = designSystem.CardStyles.CardText;
      updated._originalCardTextMuted = designSystem.CardStyles.CardTextMuted;
    }
    updated.CardStyles = { ...updated.CardStyles, ...newCardStyles };
    setDesignSystem(updated);
  };

  // Apply Global Theme Preset
  const handleApplyTheme = (themeId) => {
    setActiveTheme(themeId);
    if (themeId === 'ai-generated') {
      if (originalDesignSystem) {
        setDesignSystem(originalDesignSystem);
      }
      return;
    }

    const preset = THEME_PRESETS.find(p => p.id === themeId);
    if (!preset) return;

    setDesignSystem(prevSys => {
      if (!prevSys) return prevSys;

      const isDark = getLuminance(preset.colors.Background) < 0.4;
      const cardBg = isDark ? hexToRgba(preset.colors.Primary, 0.12) : hexToRgba(preset.colors.Primary, 0.08);
      const cardBorder = `1px solid ${isDark ? hexToRgba(preset.colors.Primary, 0.2) : hexToRgba(preset.colors.Primary, 0.12)}`;
      const cardText = isDark ? '#ffffff' : '#1f2937';
      const cardTextMuted = isDark ? 'rgba(255, 255, 255, 0.6)' : '#6b7280';

      return {
        ...prevSys,
        ColorPalette: {
          ...prevSys.ColorPalette,
          ...preset.colors
        },
        TypographyPairing: {
          ...prevSys.TypographyPairing,
          ...preset.fonts
        },
        CardStyles: {
          Background: cardBg,
          Border: cardBorder,
          CardText: cardText,
          CardTextMuted: cardTextMuted,
          BackdropFilter: 'blur(12px)'
        },
        GradientSystem: {
          BackgroundGlow: isDark 
            ? `radial-gradient(circle at top right, ${hexToRgba(preset.colors.Primary, 0.15)}, transparent 60%)` 
            : `radial-gradient(circle at top right, ${hexToRgba(preset.colors.Primary, 0.1)}, transparent 50%)`,
          CardGradient: isDark 
            ? `linear-gradient(145deg, ${preset.colors.Surface}, ${preset.colors.Background})` 
            : `linear-gradient(145deg, #ffffff, ${preset.colors.Surface})`
        }
      };
    });
  };

  // Re-compose slides helper for structural changes
  const getRawSlides = (currentSlides) => {
    return currentSlides.map(s => ({
      id: s.id,
      role: s.role,
      strategy: s.strategy,
      blocks: s.blocks.map(b => ({
        type: b.type,
        props: { ...b.props }
      }))
    }));
  };

  const reComposeSlides = (newRawSlides) => {
    if (!designDNA) return;
    const composed = composeSlides(newRawSlides, designDNA, aiAnalysis);
    const refined = critiqueAndRefine(composed);
    setSlides(refined);

    const summaryReport = refined.map(s => ({
       slide: s.id,
       role: s.role,
       method: s.strategy?.visualizationMethod || 'Editorial',
       critic: s.criticReport
    }));
    setCriticReport(summaryReport);
  };

  // Slide Organiser Operations
  const handleAddSlide = () => {
    const raw = getRawSlides(slides);
    const newSlideId = `slide-${Date.now()}`;
    const newSlide = {
      id: newSlideId,
      role: 'Content',
      strategy: { visualizationMethod: 'Editorial', imagePrompt: '', imageKeywords: [] },
      blocks: [
        { type: 'Badge', props: { text: 'New Slide' } },
        { type: 'SectionHeading', props: { text: 'Add a Catchy Title Here' } },
        { type: 'Paragraph', props: { text: 'Write some supporting body content for this slide. Keep it engaging and concise.' } }
      ]
    };
    raw.splice(activeSlideIndex + 1, 0, newSlide);
    reComposeSlides(raw);
    setActiveSlideIndex(activeSlideIndex + 1);
  };

  const handleDuplicateSlide = (index, e) => {
    e.stopPropagation();
    const raw = getRawSlides(slides);
    const sourceSlide = raw[index];
    const duplicate = JSON.parse(JSON.stringify(sourceSlide));
    duplicate.id = `slide-${Date.now()}`;
    raw.splice(index + 1, 0, duplicate);
    reComposeSlides(raw);
    setActiveSlideIndex(index + 1);
  };

  const handleDeleteSlide = (index, e) => {
    e.stopPropagation();
    if (slides.length <= 1) return;
    const raw = getRawSlides(slides);
    raw.splice(index, 1);
    reComposeSlides(raw);
    
    if (activeSlideIndex >= raw.length) {
      setActiveSlideIndex(raw.length - 1);
    } else if (activeSlideIndex === index && index > 0) {
      setActiveSlideIndex(index - 1);
    }
  };

  const handleMoveSlide = (index, direction, e) => {
    e.stopPropagation();
    const newIndex = index + direction;
    if (newIndex < 0 || newIndex >= slides.length) return;
    
    const raw = getRawSlides(slides);
    const temp = raw[index];
    raw[index] = raw[newIndex];
    raw[newIndex] = temp;
    
    reComposeSlides(raw);
    setActiveSlideIndex(newIndex);
  };

  // Slide Content Editor Operations
  const handleUpdateBlockProp = (blockIndex, propKey, value) => {
    setSlides(prevSlides => {
      const updated = [...prevSlides];
      const slide = { ...updated[activeSlideIndex] };
      
      // Update raw blocks
      slide.blocks = slide.blocks.map((b, idx) => {
        if (idx === blockIndex) {
          return {
            ...b,
            props: { ...b.props, [propKey]: value }
          };
        }
        return b;
      });

      // Update composed blocks
      slide.composedBlocks = slide.composedBlocks.map((cb, idx) => {
        if (idx === blockIndex) {
          return {
            ...cb,
            props: { ...cb.props, [propKey]: value }
          };
        }
        return cb;
      });

      updated[activeSlideIndex] = slide;
      return updated;
    });
  };

  const handleUpdateBlockPropArray = (blockIndex, propKey, itemIndex, value, action) => {
    setSlides(prevSlides => {
      const updated = [...prevSlides];
      const slide = { ...updated[activeSlideIndex] };

      const updateProps = (props) => {
        const arr = [...(props[propKey] || [])];
        if (action === 'edit') {
          arr[itemIndex] = value;
        } else if (action === 'delete') {
          arr.splice(itemIndex, 1);
        } else if (action === 'add') {
          arr.push(value || 'New Item');
        }
        return { ...props, [propKey]: arr };
      };

      slide.blocks = slide.blocks.map((b, idx) => {
        if (idx === blockIndex) {
          return { ...b, props: updateProps(b.props) };
        }
        return b;
      });

      slide.composedBlocks = slide.composedBlocks.map((cb, idx) => {
        if (idx === blockIndex) {
          return { ...cb, props: updateProps(cb.props) };
        }
        return cb;
      });

      updated[activeSlideIndex] = slide;
      return updated;
    });
  };

  // Run AI extraction and Design Generation if we arrived with a prompt
  useEffect(() => {
    if (initialPrompt && !hasContent) {
      let isMounted = true;
      
      const generate = async () => {
        try {
          const rawJson = await generateMasterCarousel(initialPrompt);
          const validationResult = validateCarouselJSON(rawJson);
          
          if (!validationResult.valid) {
            throw new Error(validationResult.error);
          }
          
          const masterData = validationResult.data;
          
          let sys;
          if (isMounted) {
            setAiAnalysis(masterData.analysis);
            setCreativeBrief(masterData.creativeBrief);
            setMoodboard(masterData.moodboard);
            setDesignDNA(masterData.designDNA);
            setStoryPlan(masterData.storyPlan);
            
            sys = await generateDesignSystem({
               Topic: masterData.analysis.topic,
               Mood: masterData.analysis.mood,
               Colors: {
                  Primary: masterData.moodboard.primaryColors[0] || '#ffffff',
                  Secondary: masterData.moodboard.primaryColors[1] || '#4f46e5'
               }
            });
            setDesignSystem(sys);
            setOriginalDesignSystem(sys);
            setActiveTheme('ai-generated');
          }

          const composedSlides = composeSlides(masterData.slides, masterData.designDNA, masterData.analysis);
          const finalRefinedSlides = critiqueAndRefine(composedSlides);
          
          if (isMounted) {
            setSlides(finalRefinedSlides);
            
            const summaryReport = finalRefinedSlides.map(s => ({
               slide: s.id,
               role: s.role,
               method: s.strategy?.visualizationMethod || 'Editorial',
               critic: s.criticReport
            }));
            setCriticReport(summaryReport);

            setActiveSlideIndex(0);
            setIsGenerating(false);
            setHasContent(true);
          }
        } catch (error) {
          console.error("AI Generation failed", error);
          if (isMounted) {
            setIsGenerating(false);
            setGenerationError(error.message);
          }
        }
      };

      generate();
      
      return () => {
        isMounted = false;
      };
    }
  }, [initialPrompt, hasContent]);

  return (
    <ErrorBoundary>
      <div className="dashboard-layout">
        {/* Left Sidebar - AI Strategy Pipeline */}
      <aside className="dashboard-sidebar left-sidebar glass">
        <div className="sidebar-header">
          <h3><Sparkles size={16} /> Creative Engine</h3>
        </div>
        <div className="sidebar-content">
          {!hasContent ? (
             <div className="json-placeholder">
               <div className="pulse-line"></div>
               <div className="pulse-line"></div>
               <div className="pulse-line" style={{ width: '60%' }}></div>
             </div>
          ) : (
            <div className="json-container" style={{ display: 'flex', flexDirection: 'column', gap: '0.5em', width: '100%', overflowX: 'hidden', flexShrink: 0 }}>
              
              {/* Theme Customizer Section */}
              <div style={{ background: 'var(--bg-tertiary)', borderRadius: 'var(--radius-md)', overflow: 'hidden', flexShrink: 0 }}>
                <button 
                  onClick={() => toggleAccordion('theme')}
                  style={{ width: '100%', display: 'flex', justifyContent: 'space-between', padding: '0.75em 1em', background: 'transparent', border: 'none', color: 'var(--text-secondary)', cursor: 'pointer', fontWeight: 'bold' }}
                >
                  <span style={{ display: 'flex', alignItems: 'center', gap: '0.5em' }}>
                    <Palette size={14} /> Carousel Theme
                  </span>
                  {openAccordions.theme ? <ChevronDown size={16} /> : <ChevronRight size={16} />}
                </button>
                {openAccordions.theme && (
                  <div style={{ padding: '0 0.75em 1.25em 0.75em', display: 'flex', flexDirection: 'column', gap: '0.5em' }}>
                    {THEME_PRESETS.map(preset => (
                      <button
                        key={preset.id}
                        onClick={() => handleApplyTheme(preset.id)}
                        style={{
                          width: '100%',
                          display: 'flex',
                          flexDirection: 'column',
                          gap: '0.25em',
                          padding: '0.75em 1em',
                          borderRadius: '8px',
                          border: activeTheme === preset.id 
                            ? '2px solid var(--brand-primary, #6366f1)' 
                            : '1px solid rgba(255,255,255,0.08)',
                          background: activeTheme === preset.id 
                            ? 'rgba(99, 102, 241, 0.12)' 
                            : 'rgba(255,255,255,0.03)',
                          color: 'var(--text-primary, #fff)',
                          cursor: 'pointer',
                          textAlign: 'left',
                          fontFamily: 'inherit',
                          transition: 'all 0.2s ease'
                        }}
                      >
                        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', width: '100%' }}>
                          <span style={{ fontWeight: '600', fontSize: '0.85em', display: 'flex', alignItems: 'center', gap: '0.4em' }}>
                            {preset.emoji} {preset.label}
                          </span>
                          {preset.colors && (
                            <div style={{ display: 'flex', gap: '4px' }}>
                              <span style={{ width: '8px', height: '8px', borderRadius: '50%', background: preset.colors.Primary }} />
                              <span style={{ width: '8px', height: '8px', borderRadius: '50%', background: preset.colors.Accent }} />
                              <span style={{ width: '8px', height: '8px', borderRadius: '50%', background: preset.colors.Background, border: '1px solid rgba(255,255,255,0.2)' }} />
                            </div>
                          )}
                        </div>
                        <span style={{ fontSize: '0.72em', color: 'var(--text-muted, #9ca3af)' }}>{preset.desc}</span>
                      </button>
                    ))}
                  </div>
                )}
              </div>

              {/* Accordions */}
              {[
                { key: 'brief', title: 'Creative Brief', data: creativeBrief },
                { key: 'moodboard', title: 'Moodboard', data: moodboard },
                { key: 'plan', title: 'Story Plan', data: storyPlan },
                { key: 'dna', title: 'Design DNA', data: designDNA },
                { key: 'critic', title: 'Design Critic QA', data: criticReport }
              ].map(section => (
                <div key={section.key} style={{ background: 'var(--bg-tertiary)', borderRadius: 'var(--radius-md)', overflow: 'hidden', flexShrink: 0 }}>
                  <button 
                    onClick={() => toggleAccordion(section.key)}
                    style={{ width: '100%', display: 'flex', justifyContent: 'space-between', padding: '0.75em 1em', background: 'transparent', border: 'none', color: 'var(--text-secondary)', cursor: 'pointer', fontWeight: 'bold' }}
                  >
                    <span>{section.title}</span>
                    {openAccordions[section.key] ? <ChevronDown size={16} /> : <ChevronRight size={16} />}
                  </button>
                  {openAccordions[section.key] && (
                    <div style={{ padding: '0 1em 1em 1em' }}>
                      <pre className="json-display" style={{ margin: 0, fontSize: '0.75em', whiteSpace: 'pre-wrap', wordBreak: 'break-all' }}>
                        {JSON.stringify(section.data, null, 2)}
                      </pre>
                    </div>
                  )}
                </div>
              ))}

              {/* Card Color Preset Customizer */}
              <div style={{ background: 'var(--bg-tertiary)', borderRadius: 'var(--radius-md)', overflow: 'hidden', marginTop: '0.5em', flexShrink: 0 }}>
                <button 
                  onClick={() => toggleAccordion('customizer')}
                  style={{ width: '100%', display: 'flex', justifyContent: 'space-between', padding: '0.75em 1em', background: 'transparent', border: 'none', color: 'var(--text-secondary)', cursor: 'pointer', fontWeight: 'bold' }}
                >
                  <span style={{ display: 'flex', alignItems: 'center', gap: '0.5em' }}>
                    <Palette size={14} /> Card Styles
                  </span>
                  {openAccordions.customizer ? <ChevronDown size={16} /> : <ChevronRight size={16} />}
                </button>
                {openAccordions.customizer && (
                  <div style={{ padding: '0 0.75em 1em 0.75em', display: 'flex', flexDirection: 'column', gap: '0.75em' }}>
                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '6px' }}>
                      {CARD_PRESETS.filter(p => p.id !== 'custom').map(preset => (
                        <button
                          key={preset.id}
                          onClick={() => applyCardPreset(preset.id)}
                          style={{
                            display: 'flex',
                            alignItems: 'center',
                            gap: '0.4em',
                            padding: '0.55em 0.65em',
                            borderRadius: '6px',
                            border: activeCardPreset === preset.id 
                              ? '2px solid var(--brand-primary, #6366f1)' 
                              : '1px solid rgba(255,255,255,0.08)',
                            background: activeCardPreset === preset.id 
                              ? 'rgba(99, 102, 241, 0.15)' 
                              : 'rgba(255,255,255,0.03)',
                            color: 'var(--text-primary, #fff)',
                            cursor: 'pointer',
                            fontSize: '0.72em',
                            fontWeight: activeCardPreset === preset.id ? '600' : '400',
                            fontFamily: 'inherit',
                            transition: 'all 0.2s ease',
                            textAlign: 'left'
                          }}
                        >
                          <span>{preset.emoji}</span>
                          <span style={{ whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{preset.label}</span>
                        </button>
                      ))}
                    </div>

                    <div style={{
                      display: 'flex',
                      alignItems: 'center',
                      gap: '0.65em',
                      padding: '0.5em 0.65em',
                      borderRadius: '6px',
                      border: activeCardPreset === 'custom' 
                        ? '2px solid var(--brand-primary, #6366f1)' 
                        : '1px solid rgba(255,255,255,0.08)',
                      background: activeCardPreset === 'custom' 
                        ? 'rgba(99, 102, 241, 0.15)' 
                        : 'rgba(255,255,255,0.03)',
                      cursor: 'pointer',
                      transition: 'all 0.2s ease'
                    }}>
                      <span style={{ fontSize: '0.72em' }}>🎯</span>
                      <input
                        type="color"
                        value={customCardHex}
                        onChange={(e) => {
                          setCustomCardHex(e.target.value);
                          applyCardPreset('custom', e.target.value);
                        }}
                        style={{
                          width: '24px',
                          height: '24px',
                          border: 'none',
                          borderRadius: '4px',
                          padding: 0,
                          cursor: 'pointer',
                          background: 'transparent'
                        }}
                      />
                      <span style={{
                        fontSize: '0.72em',
                        color: 'var(--text-primary, #fff)',
                        fontWeight: activeCardPreset === 'custom' ? '600' : '400',
                        fontFamily: 'monospace',
                        textTransform: 'uppercase'
                      }}>
                        {customCardHex}
                      </span>
                    </div>
                  </div>
                )}
              </div>

            </div>
          )}
        </div>
      </aside>

      {/* Main Workspace */}
      <main className="dashboard-workspace">
        
        {/* Workspace Toolbar */}
        <div className="workspace-toolbar glass">
          <div className="toolbar-left">
            <span className="project-title">Untitled Carousel</span>
            <span className="badge badge-draft">Draft</span>
            
            {/* Aspect Ratio Selector */}
            {hasContent && (
              <div style={{ display: 'flex', background: 'rgba(255,255,255,0.05)', borderRadius: '6px', padding: '2px', border: '1px solid rgba(255,255,255,0.08)' }}>
                <button
                  onClick={() => setAspectRatio('4:5')}
                  style={{
                    padding: '0.4em 0.8em',
                    fontSize: '0.75em',
                    borderRadius: '4px',
                    border: 'none',
                    background: aspectRatio === '4:5' ? 'var(--brand-primary, #6366f1)' : 'transparent',
                    color: '#ffffff',
                    cursor: 'pointer',
                    fontWeight: 'bold',
                    transition: 'all 0.2s'
                  }}
                >
                  Portrait 4:5
                </button>
                <button
                  onClick={() => setAspectRatio('1:1')}
                  style={{
                    padding: '0.4em 0.8em',
                    fontSize: '0.75em',
                    borderRadius: '4px',
                    border: 'none',
                    background: aspectRatio === '1:1' ? 'var(--brand-primary, #6366f1)' : 'transparent',
                    color: '#ffffff',
                    cursor: 'pointer',
                    fontWeight: 'bold',
                    transition: 'all 0.2s'
                  }}
                >
                  Square 1:1
                </button>
              </div>
            )}
          </div>
          <div className="toolbar-right" style={{ display: 'flex', gap: '0.75em' }}>
            <Button variant="secondary" size="sm" icon={<Layers size={14} />} onClick={() => setRightSidebarTab(rightSidebarTab === 'organizer' ? 'content' : 'organizer')}>
              {rightSidebarTab === 'organizer' ? 'Edit Content' : 'Slide organizer'}
            </Button>
            <div style={{ position: 'relative' }}>
              <Button 
                variant="primary" 
                size="sm" 
                icon={isExporting ? <Loader2 className="spinner animate-spin" size={14} /> : <Download size={14} />}
                onClick={() => setShowExportDropdown(!showExportDropdown)}
                disabled={isExporting}
              >
                {isExporting ? 'Exporting...' : 'Export'}
              </Button>
              
              {showExportDropdown && (
                <div className="glass" style={{
                  position: 'absolute',
                  right: 0,
                  top: 'calc(100% + 8px)',
                  background: 'var(--bg-secondary, #1e1e24)',
                  border: '1px solid rgba(255, 255, 255, 0.1)',
                  borderRadius: 'var(--radius-md, 8px)',
                  boxShadow: 'var(--sys-shadow-elevated)',
                  width: '220px',
                  zIndex: 200,
                  display: 'flex',
                  flexDirection: 'column',
                  padding: '0.4em',
                  gap: '2px',
                  pointerEvents: 'auto'
                }}>
                  <button 
                    onClick={handleExportPDF}
                    style={{
                      background: 'transparent',
                      border: 'none',
                      color: 'var(--text-primary, #ffffff)',
                      textAlign: 'left',
                      padding: '0.75em 1em',
                      borderRadius: 'var(--sys-radius-sm, 4px)',
                      cursor: 'pointer',
                      fontSize: '0.85em',
                      display: 'flex',
                      alignItems: 'center',
                      gap: '0.75em',
                      width: '100%',
                      transition: 'background 0.2s',
                      fontFamily: 'inherit'
                    }}
                    onMouseEnter={(e) => e.target.style.background = 'rgba(255, 255, 255, 0.08)'}
                    onMouseLeave={(e) => e.target.style.background = 'transparent'}
                  >
                    <SlidersHorizontal size={14} style={{ color: 'var(--brand-primary, #6366f1)' }} />
                    <span>Export as PDF (LinkedIn)</span>
                  </button>
                  <button 
                    onClick={handleExportPNGs}
                    style={{
                      background: 'transparent',
                      border: 'none',
                      color: 'var(--text-primary, #ffffff)',
                      textAlign: 'left',
                      padding: '0.75em 1em',
                      borderRadius: 'var(--sys-radius-sm, 4px)',
                      cursor: 'pointer',
                      fontSize: '0.85em',
                      display: 'flex',
                      alignItems: 'center',
                      gap: '0.75em',
                      width: '100%',
                      transition: 'background 0.2s',
                      fontFamily: 'inherit'
                    }}
                    onMouseEnter={(e) => e.target.style.background = 'rgba(255, 255, 255, 0.08)'}
                    onMouseLeave={(e) => e.target.style.background = 'transparent'}
                  >
                    <ImageIcon size={14} style={{ color: 'var(--sys-accent, #ec4899)' }} />
                    <span>Export as PNG Pack</span>
                  </button>
                </div>
              )}
            </div>
          </div>
        </div>

        {/* Editor Area */}
        <div className="editor-canvas">
          {isGenerating ? (
            <div className="state-container loading-state animate-fade-in">
              <div className="loading-icon-wrapper">
                <Loader2 className="spinner" size={48} />
                <Sparkles className="sparkle-overlay" size={20} />
              </div>
              <h2>Generating your masterpiece...</h2>
              <p>Analyzing prompt and crafting custom design elements</p>
              
              <div className="progress-bar-container">
                <div className="progress-bar-fill"></div>
              </div>
            </div>
          ) : generationError ? (
            <div className="state-container empty-state animate-fade-in" style={{ borderColor: 'var(--sys-accent)' }}>
              <div className="empty-icon-wrapper" style={{ color: 'var(--sys-accent)' }}>
                <ImageIcon size={48} />
              </div>
              <h2>Generation Failed</h2>
              <p style={{ color: 'var(--sys-accent)', maxWidth: '400px', whiteSpace: 'pre-wrap' }}>{generationError}</p>
              <Button onClick={() => setGenerationError(null)} icon={<Sparkles size={16} />}>
                Try Again
              </Button>
            </div>
          ) : !hasContent ? (
            <div className="state-container empty-state animate-fade-in">
              <div className="empty-icon-wrapper">
                <ImageIcon size={48} />
              </div>
              <h2>Ready to Create</h2>
              <p>Enter a prompt on the home page to generate a professional carousel instantly.</p>
              <Button onClick={() => window.history.back()} icon={<Sparkles size={16} />}>
                Go Generate
              </Button>
            </div>
          ) : (
            <div className="state-container generated-state animate-fade-in" style={{ width: '100%', height: '100%', maxWidth: '600px', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center' }}>
              <div className="slider-container" style={{ position: 'relative', width: '100%', height: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                {activeSlideIndex > 0 && (
                  <button 
                    onClick={() => navigateToSlide(activeSlideIndex - 1)}
                    className="slider-nav-btn prev-btn glass"
                    style={{
                      position: 'absolute', left: '-55px', zIndex: 110,
                      width: '40px', height: '40px', borderRadius: '50%',
                      display: 'flex', alignItems: 'center', justifyContent: 'center',
                      border: '1px solid rgba(255,255,255,0.1)', background: 'rgba(0,0,0,0.4)',
                      color: 'white', cursor: 'pointer', transition: 'all 0.2s ease',
                      boxShadow: 'var(--sys-shadow-soft)'
                    }}
                  >
                    <ChevronLeft size={20} />
                  </button>
                )}

                <AnimatePresence initial={false} custom={direction} mode="wait">
                  <motion.div
                    key={activeSlideIndex}
                    custom={direction}
                    variants={slideVariants}
                    initial="enter"
                    animate="center"
                    exit="exit"
                    transition={{
                      x: { type: "spring", stiffness: 300, damping: 30 },
                      opacity: { duration: 0.2 }
                    }}
                    drag="x"
                    dragConstraints={{ left: 0, right: 0 }}
                    dragElastic={0.6}
                    onDragEnd={(e, { offset }) => {
                      const swipeThreshold = 50;
                      if (offset.x < -swipeThreshold && activeSlideIndex < slides.length - 1) {
                        navigateToSlide(activeSlideIndex + 1);
                      } else if (offset.x > swipeThreshold && activeSlideIndex > 0) {
                        navigateToSlide(activeSlideIndex - 1);
                      }
                    }}
                    style={{ width: '100%', height: '100%', display: 'flex', justifyContent: 'center', alignItems: 'center', cursor: 'grab' }}
                    whileTap={{ cursor: 'grabbing' }}
                  >
                    <CarouselRenderer slide={slides[activeSlideIndex]} designSystem={designSystem} aspectRatio={aspectRatio} />
                  </motion.div>
                </AnimatePresence>

                {activeSlideIndex < slides.length - 1 && (
                  <button 
                    onClick={() => navigateToSlide(activeSlideIndex + 1)}
                    className="slider-nav-btn next-btn glass"
                    style={{
                      position: 'absolute', right: '-55px', zIndex: 110,
                      width: '40px', height: '40px', borderRadius: '50%',
                      display: 'flex', alignItems: 'center', justifyContent: 'center',
                      border: '1px solid rgba(255,255,255,0.1)', background: 'rgba(0,0,0,0.4)',
                      color: 'white', cursor: 'pointer', transition: 'all 0.2s ease',
                      boxShadow: 'var(--sys-shadow-soft)'
                    }}
                  >
                    <ChevronRight size={20} />
                  </button>
                )}
              </div>

              {/* Slider pagination dots */}
              <div style={{ display: 'flex', gap: '6px', marginTop: '1.25em', zIndex: 110, justifyContent: 'center', alignItems: 'center' }}>
                {slides.map((_, index) => (
                  <button
                    key={index}
                    onClick={() => navigateToSlide(index)}
                    style={{
                      width: index === activeSlideIndex ? '16px' : '6px',
                      height: '6px',
                      borderRadius: '3px',
                      background: index === activeSlideIndex ? 'var(--brand-primary, #6366f1)' : 'var(--text-muted, #9ca3af)',
                      opacity: index === activeSlideIndex ? 1 : 0.4,
                      border: 'none',
                      padding: 0,
                      cursor: 'pointer',
                      transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)'
                    }}
                  />
                ))}
              </div>
            </div>
          )}
        </div>
      </main>

      {/* Right Sidebar - Slide Organizer & Content Editor */}
      <aside className="dashboard-sidebar right-sidebar glass" style={{ width: '310px' }}>
         <div className="sidebar-header" style={{ display: 'flex', flexDirection: 'column', gap: '8px', padding: '12px 16px' }}>
          <div style={{ display: 'flex', background: 'rgba(255,255,255,0.05)', borderRadius: '6px', padding: '2px', width: '100%' }}>
            <button
              onClick={() => setRightSidebarTab('organizer')}
              style={{
                flex: 1,
                padding: '0.5em',
                fontSize: '0.8em',
                borderRadius: '4px',
                border: 'none',
                background: rightSidebarTab === 'organizer' ? 'rgba(255,255,255,0.1)' : 'transparent',
                color: rightSidebarTab === 'organizer' ? '#ffffff' : 'var(--text-secondary)',
                cursor: 'pointer',
                fontWeight: 'bold',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                gap: '0.4em'
              }}
            >
              <Layers size={13} /> Organizer
            </button>
            <button
              onClick={() => setRightSidebarTab('content')}
              style={{
                flex: 1,
                padding: '0.5em',
                fontSize: '0.8em',
                borderRadius: '4px',
                border: 'none',
                background: rightSidebarTab === 'content' ? 'rgba(255,255,255,0.1)' : 'transparent',
                color: rightSidebarTab === 'content' ? '#ffffff' : 'var(--text-secondary)',
                cursor: 'pointer',
                fontWeight: 'bold',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                gap: '0.4em'
              }}
            >
              <Edit size={13} /> Edit Content
            </button>
          </div>
        </div>
        
        <div className="sidebar-content" style={{ padding: '12px 16px' }}>
          {slides.length > 0 ? (
            rightSidebarTab === 'organizer' ? (
              // ORGANISER VIEW
              <div style={{ display: 'flex', flexDirection: 'column', gap: '10px', width: '100%' }}>
                {slides.map((slide, index) => (
                  <div 
                    key={slide.id} 
                    className={`slide-thumb-placeholder ${index === activeSlideIndex ? 'active' : ''}`}
                    onClick={() => navigateToSlide(index)}
                    style={{ 
                      display: 'flex', 
                      flexDirection: 'column', 
                      justifyContent: 'space-between', 
                      padding: '0.85em',
                      background: index === activeSlideIndex ? 'rgba(255,255,255,0.08)' : 'var(--bg-tertiary)',
                      border: index === activeSlideIndex ? '1.5px solid var(--brand-primary)' : '1px solid rgba(255,255,255,0.05)',
                      borderRadius: '8px',
                      cursor: 'pointer',
                      position: 'relative',
                      height: '95px',
                      overflow: 'hidden',
                      transition: 'all 0.2s ease'
                    }}
                  >
                    {/* Top Row: Slide number & role */}
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', width: '100%' }}>
                      <span style={{ fontSize: '0.9em', fontWeight: 'bold', color: index === activeSlideIndex ? 'var(--brand-primary)' : 'var(--text-muted)' }}>
                        Slide {index + 1}
                      </span>
                      <span style={{ fontSize: '0.7em', padding: '2px 6px', background: 'rgba(255,255,255,0.05)', borderRadius: '4px', textTransform: 'uppercase', color: 'var(--text-secondary)' }}>
                        {slide.role}
                      </span>
                    </div>

                    {/* Middle: Truncated content preview */}
                    <div style={{ fontSize: '0.72em', color: 'var(--text-muted)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', width: '100%' }}>
                      {slide.blocks.find(b => b.type === 'SectionHeading' || b.type === 'HeroHeading')?.props?.text || 'Empty Heading'}
                    </div>

                    {/* Bottom Row: Actions */}
                    <div style={{ display: 'flex', gap: '8px', alignSelf: 'flex-end', marginTop: '4px' }}>
                      <button
                        title="Move Up"
                        disabled={index === 0}
                        onClick={(e) => handleMoveSlide(index, -1, e)}
                        style={{ background: 'transparent', border: 'none', color: index === 0 ? 'rgba(255,255,255,0.1)' : 'var(--text-muted)', cursor: index === 0 ? 'not-allowed' : 'pointer', padding: '2px' }}
                      >
                        <ArrowUp size={14} />
                      </button>
                      <button
                        title="Move Down"
                        disabled={index === slides.length - 1}
                        onClick={(e) => handleMoveSlide(index, 1, e)}
                        style={{ background: 'transparent', border: 'none', color: index === slides.length - 1 ? 'rgba(255,255,255,0.1)' : 'var(--text-muted)', cursor: index === slides.length - 1 ? 'not-allowed' : 'pointer', padding: '2px' }}
                      >
                        <ArrowDown size={14} />
                      </button>
                      <button
                        title="Duplicate Slide"
                        onClick={(e) => handleDuplicateSlide(index, e)}
                        style={{ background: 'transparent', border: 'none', color: 'var(--text-muted)', cursor: 'pointer', padding: '2px' }}
                      >
                        <Copy size={14} />
                      </button>
                      <button
                        title="Delete Slide"
                        disabled={slides.length <= 1}
                        onClick={(e) => handleDeleteSlide(index, e)}
                        style={{ background: 'transparent', border: 'none', color: slides.length <= 1 ? 'rgba(255,255,255,0.1)' : '#f87171', cursor: slides.length <= 1 ? 'not-allowed' : 'pointer', padding: '2px' }}
                      >
                        <Trash2 size={14} />
                      </button>
                    </div>
                  </div>
                ))}
                
                <button 
                  onClick={handleAddSlide}
                  className="add-slide-btn"
                  style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.5em', marginTop: '4px', cursor: 'pointer' }}
                >
                  <Plus size={16} /> Add Slide
                </button>
              </div>
            ) : (
              // EDIT SLIDE CONTENT VIEW
              <div style={{ display: 'flex', flexDirection: 'column', gap: '1.25em', width: '100%' }}>
                <div style={{ borderBottom: '1px solid rgba(255,255,255,0.08)', paddingBottom: '0.75em' }}>
                  <div style={{ fontSize: '0.85em', color: 'var(--text-muted)' }}>Slide Role</div>
                  <div style={{ fontSize: '1em', fontWeight: 'bold', color: 'var(--brand-primary)', textTransform: 'uppercase', marginTop: '2px' }}>
                    {slides[activeSlideIndex].role}
                  </div>
                </div>

                {slides[activeSlideIndex].blocks.map((block, blockIndex) => {
                  return (
                    <div 
                      key={`${block.type}-${blockIndex}`} 
                      style={{ 
                        background: 'rgba(255,255,255,0.02)', 
                        border: '1px solid rgba(255,255,255,0.05)', 
                        borderRadius: '6px', 
                        padding: '0.75em' 
                      }}
                    >
                      <div style={{ fontSize: '0.72em', fontWeight: 'bold', textTransform: 'uppercase', letterSpacing: '0.05em', color: 'var(--brand-primary)', marginBottom: '0.5em' }}>
                        {block.type}
                      </div>

                      <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5em' }}>
                        {Object.entries(block.props).map(([propKey, propVal]) => {
                          if (Array.isArray(propVal)) {
                            // If it's a list (array of strings)
                            return (
                              <div key={propKey} style={{ display: 'flex', flexDirection: 'column', gap: '4px' }}>
                                <span style={{ fontSize: '0.75em', color: 'var(--text-secondary)' }}>{propKey}</span>
                                {propVal.map((item, itemIdx) => (
                                  <div key={itemIdx} style={{ display: 'flex', gap: '4px', alignItems: 'center' }}>
                                    <input 
                                      type="text"
                                      value={item}
                                      onChange={(e) => handleUpdateBlockPropArray(blockIndex, propKey, itemIdx, e.target.value, 'edit')}
                                      style={{
                                        flex: 1,
                                        background: 'var(--bg-tertiary)',
                                        border: '1px solid rgba(255,255,255,0.08)',
                                        borderRadius: '4px',
                                        padding: '4px 8px',
                                        color: '#ffffff',
                                        fontSize: '0.8em',
                                        outline: 'none'
                                      }}
                                    />
                                    <button 
                                      onClick={() => handleUpdateBlockPropArray(blockIndex, propKey, itemIdx, null, 'delete')}
                                      style={{ background: 'transparent', border: 'none', color: '#f87171', cursor: 'pointer', fontSize: '0.85em', padding: '2px' }}
                                    >
                                      ✕
                                    </button>
                                  </div>
                                ))}
                                <button 
                                  onClick={() => handleUpdateBlockPropArray(blockIndex, propKey, null, 'New Item', 'add')}
                                  style={{
                                    alignSelf: 'flex-start',
                                    fontSize: '0.7em',
                                    background: 'rgba(255,255,255,0.05)',
                                    color: 'var(--text-primary)',
                                    border: '1px solid rgba(255,255,255,0.08)',
                                    borderRadius: '4px',
                                    padding: '2px 8px',
                                    marginTop: '2px',
                                    cursor: 'pointer'
                                  }}
                                >
                                  + Add Item
                                </button>
                              </div>
                            );
                          } else {
                            // If it's a simple string / number
                            const isTextarea = propKey === 'text' || propKey === 'quote' || propKey === 'subtitle' || propKey === 'leftText' || propKey === 'rightText' || propKey === 'code';
                            return (
                              <label key={propKey} style={{ display: 'flex', flexDirection: 'column', gap: '4px' }}>
                                <span style={{ fontSize: '0.75em', color: 'var(--text-secondary)' }}>{propKey}</span>
                                {isTextarea ? (
                                  <textarea
                                    rows={3}
                                    value={propVal}
                                    onChange={(e) => handleUpdateBlockProp(blockIndex, propKey, e.target.value)}
                                    style={{
                                      background: 'var(--bg-tertiary)',
                                      border: '1px solid rgba(255,255,255,0.08)',
                                      borderRadius: '4px',
                                      padding: '6px 8px',
                                      color: '#ffffff',
                                      fontSize: '0.8em',
                                      outline: 'none',
                                      resize: 'vertical',
                                      fontFamily: propKey === 'code' ? 'monospace' : 'inherit'
                                    }}
                                  />
                                ) : (
                                  <input 
                                    type="text"
                                    value={propVal}
                                    onChange={(e) => handleUpdateBlockProp(blockIndex, propKey, e.target.value)}
                                    style={{
                                      background: 'var(--bg-tertiary)',
                                      border: '1px solid rgba(255,255,255,0.08)',
                                      borderRadius: '4px',
                                      padding: '6px 8px',
                                      color: '#ffffff',
                                      fontSize: '0.8em',
                                      outline: 'none'
                                    }}
                                  />
                                )}
                              </label>
                            );
                          }
                        })}
                      </div>
                    </div>
                  );
                })}
              </div>
            )
          ) : (
            <div style={{ color: 'var(--text-muted)', fontSize: '0.85em', textAlign: 'center', marginTop: '2em' }}>
              No slides generated yet.
            </div>
          )}
        </div>
      </aside>
      </div>
    </ErrorBoundary>
  );
}
